// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omatcnxdwftllnemhfeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYXRjbnhkd2Z0bGxuZW1oZmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDQ0NzAsImV4cCI6MjA3Mzc4MDQ3MH0.DnpylNbkAl5n9UOVwXCG4l1p7cz_k8eDaMl_U-oZlDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
